services:

  app:
    build:
      context: .
      dockerfile: dockerfile

    container_name: laravel_app

    volumes:
      - ./:/var/www:cached

    networks:
      - laravel

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx

    container_name: laravel_nginx

    ports:
      - "8001:80"

    depends_on:
      - app

    networks:
      - laravel

  mysql:
    image: mysql:8

    container_name: laravel_mysql

    restart: always

    environment:
      MYSQL_DATABASE: db_samsimga
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    networks:
      - laravel

  npm:
    image: node:20

    container_name: laravel_npm

    working_dir: /var/www

    volumes:
      - ./:/var/www:cached
      - /var/www/node_modules

    ports:
      - "5173:5173"

    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

    networks:
      - laravel

  ai_prediction:
    image: sihiy1/ai-stock-prediction:latest

    container_name: ai_prediction

    restart: always

    ports:
      - "8002:8001"

    networks:
      - laravel

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins

    container_name: jenkins

    restart: always

    user: root

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - laravel

  prometheus:
    image: prom/prometheus:latest

    container_name: prometheus

    restart: always

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    networks:
      - laravel

  grafana:
    image: grafana/grafana:latest

    container_name: grafana

    restart: always

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    ports:
      - "3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - prometheus

    networks:
      - laravel

volumes:
  jenkins_home:
  prometheus_data:
  grafana_data:

networks:
  laravel:
