version: '3.9'

services:

  app:
    image: sihiy1/sasimga-jember:latest
    environment:
      APP_ENV: production
      APP_DEBUG: "true"

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: db_samsimga
      DB_USERNAME: root
      DB_PASSWORD: root

    depends_on:
      - mysql


    volumes:
      - laravel_data:/var/www

    networks:
      - laravel


  nginx:
    image: sihiy1/sasimga-nginx:latest
    ports:
      - "80:80"

    volumes:
      - laravel_data:/var/www

    depends_on:
      - app

    networks:
      - laravel

  mysql:
    image: mysql:8

    restart: always

    environment:
      MYSQL_DATABASE: db_samsimga
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    networks:
      - laravel

volumes:
  laravel_data:

networks:
  laravel:
    driver: overlay
