FROM node:20 AS node_builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY public /var/www/public
COPY --from=node_builder /app/public/build /var/www/public/build
