services:

  app:
    build:
      context: .
      dockerfile: dockerfile

    container_name: laravel_app

    volumes:
      - ./:/var/www:cached

    networks:
      - laravel

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx

    container_name: laravel_nginx

    ports:
      - "8001:80"

    depends_on:
      - app

    networks:
      - laravel

  mysql:
    image: mysql:8

    container_name: laravel_mysql

    restart: always

    environment:
      MYSQL_DATABASE: db_samsimga
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    networks:
      - laravel

  npm:
    image: node:20

    container_name: laravel_npm

    working_dir: /var/www

    volumes:
      - ./:/var/www:cached
      - /var/www/node_modules

    ports:
      - "5173:5173"

    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

    networks:
      - laravel

  ai_prediction:
    image: sihiy1/ai-stock-prediction:latest

    container_name: ai_prediction

    restart: always

    ports:
      - "8002:8001"

    networks:
      - laravel

networks:
  laravel:
